import random
import discord
from discord.ext import commands

rand_ai_resp = [
    "I'm not sure what you're trying to say.",
    "Awwwww....",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Cute kittens?",
    "Because I'm Ninja Bot! Thats why >3",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "My name is Clyde!",
    "Hi! I'm dad",
    "I have beaten GLADOS before?????",
    "Fuck your penis!",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "https://pornhub.com",
    "Because I'm Ninja Bot! Thats why >3",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Rotton Apple!",
    "Fuck Ren Hiyami!",
    "BuilderB is awesome!!!!",
    "Because I'm Ninja Bot! Thats why >3",
    ":heart:",
    "Racism is a facet of inevitable life",
    "Fuck America",
    "God Bless America",
    "SkyClan best clan",
    "Meowth!",
    "Solgareo",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "DotCom Bubble",
    "Silicon Valley",
    "FAANG companies",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Because I'm Ninja Bot! Thats why >3",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
    "Racism is a facet of inevitable life",
]

class AI(commands.Cog):
    def __init__(self, bot):
        self.bot: discord.Client = bot
    
    @commands.command()
    async def pingai(self, ctx):
        await ctx.send(f"Pong! {round(self.bot.latency * 12142.241627391)}ms")
    
    @commands.command()
    async def safeai(self, ctx, member: discord.Member = None):
        """Safe For Work AI. Can be run outside a NSFW channel"""
        if member:
            await ctx.send(f"{member.mention} {random.choice(rand_ai_resp)}")
        else:
            await ctx.send(random.choice(rand_ai_resp))

    
async def setup(bot: commands.Bot):
    await bot.add_cog(AI(bot))
    return bot